-- Users table (managed by Supabase Auth)
-- Note: Supabase automatically creates a `users` table in the `auth` schema.
-- We can add a public `profiles` table to store additional user data.

CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users(id) PRIMARY KEY,
  username text,
  full_name text,
  avatar_url text,
  updated_at timestamptz DEFAULT now()
);

-- Projects table
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  name text NOT NULL,
  system_type text NOT NULL,
  kp float NOT NULL,
  ki float NOT NULL,
  kd float NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Session history (optional)
CREATE TABLE public.session_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint REFERENCES public.projects(id),
  input_data jsonb,
  output_data jsonb,
  explanation text,
  created_at timestamptz DEFAULT now()
);
